//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/* Edited by Robbie */

namespace TravelExpertsWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }

        [DisplayName("Booking ID")]
        public int BookingId { get; set; }

        [DisplayName("Booking Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> BookingDate { get; set; }

        [DisplayName("Booking Number")]
        public string BookingNo { get; set; }

        [DisplayName("Number of Travelers")]
        public Nullable<double> TravelerCount { get; set; }

        [DisplayName("Customer ID")]
        public Nullable<int> CustomerId { get; set; }

        [DisplayName("Trip Type ID")]
        public string TripTypeId { get; set; }

        [DisplayName("Package ID")]
        public Nullable<int> PackageId { get; set; }

        [DisplayName("Base Price")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> BasePrice { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Package Package { get; set; }
        public virtual TripType TripType { get; set; }
    }
}
