//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExpertsWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Products
    {
        public int PackageId { get; set; }
        public Nullable<int> Prod1 { get; set; }
        public Nullable<int> Prod2 { get; set; }
        public Nullable<int> Prod3 { get; set; }
    }
}
