//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/* Edited by Robbie */

namespace TravelExpertsWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Bookings = new HashSet<Booking>();
            this.Products_Suppliers = new HashSet<Products_Suppliers>();
        }

        public int PackageId { get; set; }

        [DisplayName("Package Name")]
        public string PkgName { get; set; }

        [DisplayName("Start Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PkgStartDate { get; set; }

        [DisplayName("End Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PkgEndDate { get; set; }

        [DisplayName("Description")]
        public string PkgDesc { get; set; }

        [DisplayName("Price")]
        [DataType(DataType.Currency)]
        public decimal PkgBasePrice { get; set; }
        public Nullable<decimal> PkgAgencyCommission { get; set; }
        public string PkgImage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Suppliers> Products_Suppliers { get; set; }
    }
}
